# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93abe70a7725539c3017ef462636f999585b6beaebf4820854d71c4cf77d796f97064dc5de09d1c7aec3303ddf4afe99da7c0831dab6c8675e69576b33a31dc6

test:
  secret_key_base: 2a791319842c0b54b88f9e417e0d8f1bea0fc6d2797bcbe94bebc826785e77ce80dffb6d58d8983aa55e445a83ec3fc5a9e5f0e17f4426297e31039ea1e0b4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
